//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Anton/Inputsystemtest/DroneControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @DroneControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @DroneControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""DroneControls"",
    ""maps"": [
        {
            ""name"": ""Drone1"",
            ""id"": ""37efff80-8416-470f-91ea-c8884224969f"",
            ""actions"": [
                {
                    ""name"": ""Acend"",
                    ""type"": ""Value"",
                    ""id"": ""789c9b7f-15c7-4d4e-9061-73a94a7e5a52"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Decend"",
                    ""type"": ""Value"",
                    ""id"": ""e4d09feb-f009-4803-9e9c-ea6818be1dd8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""ae89e56c-aef3-4af6-95c4-7010972dd8bf"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Move1"",
                    ""type"": ""Value"",
                    ""id"": ""c14ce421-b094-44f1-88ca-ca4e600af9bf"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Grow"",
                    ""type"": ""Button"",
                    ""id"": ""ef3a1be8-453e-480c-8685-42fe7e6fb492"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c8daa41d-5d48-44cc-9ee3-025c5da7086b"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Acend"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3a48694-5ab1-486e-89f6-a733ba2bb6b3"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Decend"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""738c7e31-537c-43ec-9eee-f9db3be9dd0b"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""56062768-e282-4e81-a0c4-e53604728e77"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""63a1c4cd-7552-48d5-b2ac-0fa874485d46"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Drone2"",
            ""id"": ""fa21216b-4439-4160-89ae-24dc1fb23ec4"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""307fb7cd-4406-4c32-a7cf-dead583424a6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Right_X"",
                    ""id"": ""c86160f0-7cd7-4f40-9357-e1a367645557"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""adce9eae-fec6-417c-a2e5-32df3f771cb8"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""1614784d-478b-4951-83af-4979d942cc1d"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Drone1
        m_Drone1 = asset.FindActionMap("Drone1", throwIfNotFound: true);
        m_Drone1_Acend = m_Drone1.FindAction("Acend", throwIfNotFound: true);
        m_Drone1_Decend = m_Drone1.FindAction("Decend", throwIfNotFound: true);
        m_Drone1_Rotate = m_Drone1.FindAction("Rotate", throwIfNotFound: true);
        m_Drone1_Move1 = m_Drone1.FindAction("Move1", throwIfNotFound: true);
        m_Drone1_Grow = m_Drone1.FindAction("Grow", throwIfNotFound: true);
        // Drone2
        m_Drone2 = asset.FindActionMap("Drone2", throwIfNotFound: true);
        m_Drone2_Move = m_Drone2.FindAction("Move", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Drone1
    private readonly InputActionMap m_Drone1;
    private List<IDrone1Actions> m_Drone1ActionsCallbackInterfaces = new List<IDrone1Actions>();
    private readonly InputAction m_Drone1_Acend;
    private readonly InputAction m_Drone1_Decend;
    private readonly InputAction m_Drone1_Rotate;
    private readonly InputAction m_Drone1_Move1;
    private readonly InputAction m_Drone1_Grow;
    public struct Drone1Actions
    {
        private @DroneControls m_Wrapper;
        public Drone1Actions(@DroneControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Acend => m_Wrapper.m_Drone1_Acend;
        public InputAction @Decend => m_Wrapper.m_Drone1_Decend;
        public InputAction @Rotate => m_Wrapper.m_Drone1_Rotate;
        public InputAction @Move1 => m_Wrapper.m_Drone1_Move1;
        public InputAction @Grow => m_Wrapper.m_Drone1_Grow;
        public InputActionMap Get() { return m_Wrapper.m_Drone1; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Drone1Actions set) { return set.Get(); }
        public void AddCallbacks(IDrone1Actions instance)
        {
            if (instance == null || m_Wrapper.m_Drone1ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Drone1ActionsCallbackInterfaces.Add(instance);
            @Acend.started += instance.OnAcend;
            @Acend.performed += instance.OnAcend;
            @Acend.canceled += instance.OnAcend;
            @Decend.started += instance.OnDecend;
            @Decend.performed += instance.OnDecend;
            @Decend.canceled += instance.OnDecend;
            @Rotate.started += instance.OnRotate;
            @Rotate.performed += instance.OnRotate;
            @Rotate.canceled += instance.OnRotate;
            @Move1.started += instance.OnMove1;
            @Move1.performed += instance.OnMove1;
            @Move1.canceled += instance.OnMove1;
            @Grow.started += instance.OnGrow;
            @Grow.performed += instance.OnGrow;
            @Grow.canceled += instance.OnGrow;
        }

        private void UnregisterCallbacks(IDrone1Actions instance)
        {
            @Acend.started -= instance.OnAcend;
            @Acend.performed -= instance.OnAcend;
            @Acend.canceled -= instance.OnAcend;
            @Decend.started -= instance.OnDecend;
            @Decend.performed -= instance.OnDecend;
            @Decend.canceled -= instance.OnDecend;
            @Rotate.started -= instance.OnRotate;
            @Rotate.performed -= instance.OnRotate;
            @Rotate.canceled -= instance.OnRotate;
            @Move1.started -= instance.OnMove1;
            @Move1.performed -= instance.OnMove1;
            @Move1.canceled -= instance.OnMove1;
            @Grow.started -= instance.OnGrow;
            @Grow.performed -= instance.OnGrow;
            @Grow.canceled -= instance.OnGrow;
        }

        public void RemoveCallbacks(IDrone1Actions instance)
        {
            if (m_Wrapper.m_Drone1ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDrone1Actions instance)
        {
            foreach (var item in m_Wrapper.m_Drone1ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Drone1ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Drone1Actions @Drone1 => new Drone1Actions(this);

    // Drone2
    private readonly InputActionMap m_Drone2;
    private List<IDrone2Actions> m_Drone2ActionsCallbackInterfaces = new List<IDrone2Actions>();
    private readonly InputAction m_Drone2_Move;
    public struct Drone2Actions
    {
        private @DroneControls m_Wrapper;
        public Drone2Actions(@DroneControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Drone2_Move;
        public InputActionMap Get() { return m_Wrapper.m_Drone2; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Drone2Actions set) { return set.Get(); }
        public void AddCallbacks(IDrone2Actions instance)
        {
            if (instance == null || m_Wrapper.m_Drone2ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Drone2ActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IDrone2Actions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IDrone2Actions instance)
        {
            if (m_Wrapper.m_Drone2ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDrone2Actions instance)
        {
            foreach (var item in m_Wrapper.m_Drone2ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Drone2ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Drone2Actions @Drone2 => new Drone2Actions(this);
    public interface IDrone1Actions
    {
        void OnAcend(InputAction.CallbackContext context);
        void OnDecend(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
        void OnMove1(InputAction.CallbackContext context);
        void OnGrow(InputAction.CallbackContext context);
    }
    public interface IDrone2Actions
    {
        void OnMove(InputAction.CallbackContext context);
    }
}
